# Generated by Django 4.2.7 on 2024-06-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
