# Generated by Django 4.2.7 on 2024-06-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0003_friend_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
