# Generated by Django 4.2.7 on 2024-07-16 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mychatapp', '0011_friendconnect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendconnect',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
