# Generated by Django 4.2.7 on 2024-07-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0012_alter_friendconnect_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendConnect',
        ),
    ]
