# Generated by Django 4.2.7 on 2024-07-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0013_delete_friendconnect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
